python ../database/mongo_to_csv/create_profiles_csv.py
python ../database/mongo_to_csv/create_products_csv.py
python ../database/mongo_to_csv/create_sessions_csv.py
python ../database/mongo_to_csv/create_viewed_before_csv.py
python ../database/mongo_to_csv/create_order_csv.py
python ../database/mongo_to_csv/create_viewed_brand_csv.py
python ../database/mongo_to_csv/create_viewed_category_csv.py
python ../database/mongo_to_csv/create_viewed_gender_csv.py
python ../database/mongo_to_csv/create_viewed_sub_category.py
python ../database/mongo_to_csv/create_viewed_sub_sub_category.py
python ../database/mongo_to_csv/create_viewed_promos.py
python ../database/mongo_to_csv/create_viewed_type.py
python ../database/mongo_to_csv/create_viewed_product_type.py
python ../database/mongo_to_csv/create_viewed_product_size.py