python ../database/mongo_to_csv/create_profiles_csv.py
python ../database/mongo_to_csv/create_products_csv.py
python ../database/mongo_to_csv/create_sessions_csv_improved.py
python ../database/mongo_to_csv/create_viewed_before_csv.py
python ../database/mongo_to_csv/create_order_csv.py
python ../database/mongo_to_csv/create_viewed_brand_csv.py
python ../database/mongo_to_csv/create_viewed_category_csv.py
python ../database/mongo_to_csv/create_viewed_gender_csv.py
python ../database/mongo_to_csv/create_viewed_sub_category_csv.py
python ../database/mongo_to_csv/create_viewed_sub_sub_category_csv.py
python ../database/mongo_to_csv/create_viewed_promos_csv.py
python ../database/mongo_to_csv/create_viewed_type_csv.py
python ../database/mongo_to_csv/create_viewed_product_type_csv.py
python ../database/mongo_to_csv/create_viewed_product_size_csv.py