"""Added viewed product type

Revision ID: 07162416247f
Revises: e6118c865262
Create Date: 2020-03-24 17:06:20.236661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07162416247f'
down_revision = 'e6118c865262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewed_product_type',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('product_type_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.profile_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewed_product_type')
    # ### end Alembic commands ###
