"""Changing foreign keys from profile_id to session_id

Revision ID: 08900a90d6a1
Revises: 832e4dd8fb03
Create Date: 2020-04-02 13:21:46.158318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08900a90d6a1'
down_revision = '832e4dd8fb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewed_before',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.alter_column('previously_recommended', 'profile_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('viewed_brand_ibfk_1', 'viewed_brand', type_='foreignkey')
    op.create_foreign_key(None, 'viewed_brand', 'sessions', ['session_id'], ['session_id'])
    op.drop_constraint('viewed_category_ibfk_1', 'viewed_category', type_='foreignkey')
    op.create_foreign_key(None, 'viewed_category', 'sessions', ['session_id'], ['session_id'])
    op.drop_constraint('viewed_gender_ibfk_1', 'viewed_gender', type_='foreignkey')
    op.create_foreign_key(None, 'viewed_gender', 'sessions', ['session_id'], ['session_id'])
    op.drop_constraint('viewed_product_size_ibfk_1', 'viewed_product_size', type_='foreignkey')
    op.create_foreign_key(None, 'viewed_product_size', 'sessions', ['session_id'], ['session_id'])
    op.drop_constraint('viewed_product_type_ibfk_1', 'viewed_product_type', type_='foreignkey')
    op.create_foreign_key(None, 'viewed_product_type', 'sessions', ['session_id'], ['session_id'])
    op.drop_constraint('viewed_promos_ibfk_1', 'viewed_promos', type_='foreignkey')
    op.create_foreign_key(None, 'viewed_promos', 'sessions', ['session_id'], ['session_id'])
    op.drop_constraint('viewed_sub_category_ibfk_1', 'viewed_sub_category', type_='foreignkey')
    op.create_foreign_key(None, 'viewed_sub_category', 'sessions', ['session_id'], ['session_id'])
    op.drop_constraint('viewed_sub_sub_category_ibfk_1', 'viewed_sub_sub_category', type_='foreignkey')
    op.create_foreign_key(None, 'viewed_sub_sub_category', 'sessions', ['session_id'], ['session_id'])
    op.drop_constraint('viewed_type_ibfk_1', 'viewed_type', type_='foreignkey')
    op.create_foreign_key(None, 'viewed_type', 'sessions', ['session_id'], ['session_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'viewed_type', type_='foreignkey')
    op.create_foreign_key('viewed_type_ibfk_1', 'viewed_type', 'sessions', ['session_id'], ['profile_id'])
    op.drop_constraint(None, 'viewed_sub_sub_category', type_='foreignkey')
    op.create_foreign_key('viewed_sub_sub_category_ibfk_1', 'viewed_sub_sub_category', 'sessions', ['session_id'], ['profile_id'])
    op.drop_constraint(None, 'viewed_sub_category', type_='foreignkey')
    op.create_foreign_key('viewed_sub_category_ibfk_1', 'viewed_sub_category', 'sessions', ['session_id'], ['profile_id'])
    op.drop_constraint(None, 'viewed_promos', type_='foreignkey')
    op.create_foreign_key('viewed_promos_ibfk_1', 'viewed_promos', 'sessions', ['session_id'], ['profile_id'])
    op.drop_constraint(None, 'viewed_product_type', type_='foreignkey')
    op.create_foreign_key('viewed_product_type_ibfk_1', 'viewed_product_type', 'sessions', ['session_id'], ['profile_id'])
    op.drop_constraint(None, 'viewed_product_size', type_='foreignkey')
    op.create_foreign_key('viewed_product_size_ibfk_1', 'viewed_product_size', 'sessions', ['session_id'], ['profile_id'])
    op.drop_constraint(None, 'viewed_gender', type_='foreignkey')
    op.create_foreign_key('viewed_gender_ibfk_1', 'viewed_gender', 'sessions', ['session_id'], ['profile_id'])
    op.drop_constraint(None, 'viewed_category', type_='foreignkey')
    op.create_foreign_key('viewed_category_ibfk_1', 'viewed_category', 'sessions', ['session_id'], ['profile_id'])
    op.drop_constraint(None, 'viewed_brand', type_='foreignkey')
    op.create_foreign_key('viewed_brand_ibfk_1', 'viewed_brand', 'sessions', ['session_id'], ['profile_id'])
    op.alter_column('previously_recommended', 'profile_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_table('viewed_before')
    # ### end Alembic commands ###
