"""Added fields to sessions

Revision ID: 2d53a67e4d71
Revises: ea4c6f39f70f
Create Date: 2020-03-24 17:15:10.895056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d53a67e4d71'
down_revision = 'ea4c6f39f70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('session_end', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('session_start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'session_start')
    op.drop_column('sessions', 'session_end')
    # ### end Alembic commands ###
