"""Added viewed gender

Revision ID: 485614ac9da2
Revises: 1036c6ce27d9
Create Date: 2020-03-24 16:52:29.340569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485614ac9da2'
down_revision = '1036c6ce27d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewed_gender',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('gender_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.profile_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewed_gender')
    # ### end Alembic commands ###
