"""Added user agent

Revision ID: 507d5d41780e
Revises: fb3e83670045
Create Date: 2020-03-24 16:31:22.544770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507d5d41780e'
down_revision = 'fb3e83670045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_agent',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('os_family', sa.String(length=255), nullable=True),
    sa.Column('browser_family', sa.String(length=255), nullable=True),
    sa.Column('device_brandutel', sa.String(length=255), nullable=True),
    sa.Column('is_botutel', sa.Boolean(), nullable=True),
    sa.Column('is_email_clientutel', sa.Boolean(), nullable=True),
    sa.Column('is_mobileutel', sa.Boolean(), nullable=True),
    sa.Column('is_pcutel', sa.Boolean(), nullable=True),
    sa.Column('is_tableutel', sa.Boolean(), nullable=True),
    sa.Column('istouchutel', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.profile_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_agent')
    # ### end Alembic commands ###
