"""Added properties

Revision ID: 5c5ecac14904
Revises: bcaefeea28f8
Create Date: 2020-03-24 15:46:48.355996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5ecac14904'
down_revision = 'bcaefeea28f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('profile_id', sa.String(length=255), nullable=False),
    sa.Column('availablity', sa.String(length=255), nullable=True),
    sa.Column('discount', sa.String(length=255), nullable=True),
    sa.Column('target_group', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('online_only', sa.Boolean(), nullable=True),
    sa.Column('series', sa.String(length=255), nullable=True),
    sa.Column('sort', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('variant', sa.String(length=255), nullable=True),
    sa.Column('fragrance_type', sa.String(length=255), nullable=True),
    sa.Column('type_hair_care', sa.String(length=255), nullable=True),
    sa.Column('type_hair_color', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
