"""Added products

Revision ID: 6c073196c083
Revises: e2de9f1ed176
Create Date: 2020-03-24 15:13:36.281510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c073196c083'
down_revision = 'e2de9f1ed176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('selling_price', sa.Integer(), nullable=True),
    sa.Column('recommandable', sa.Boolean(), nullable=True),
    sa.Column('sub_category', sa.String(length=255), nullable=True),
    sa.Column('sub_sub_category', sa.String(length=255), nullable=True),
    sa.Column('sub_sub_sub_category', sa.String(length=255), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
