"""Merged properties into products

Revision ID: 6cde90898bae
Revises: 507d5d41780e
Create Date: 2020-03-24 16:45:44.971100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6cde90898bae'
down_revision = '507d5d41780e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewed_brand',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.profile_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.drop_table('properties')
    op.add_column('products', sa.Column('availablity', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('fragrance_type', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('online_only', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('series', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('sort', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('target_group', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('type', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('type_hair_care', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('type_hair_color', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('unit', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('variant', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'variant')
    op.drop_column('products', 'unit')
    op.drop_column('products', 'type_hair_color')
    op.drop_column('products', 'type_hair_care')
    op.drop_column('products', 'type')
    op.drop_column('products', 'target_group')
    op.drop_column('products', 'sort')
    op.drop_column('products', 'series')
    op.drop_column('products', 'online_only')
    op.drop_column('products', 'fragrance_type')
    op.drop_column('products', 'availablity')
    op.create_table('properties',
    sa.Column('profile_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('availablity', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('discount', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('target_group', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('online_only', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('series', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sort', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('variant', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fragrance_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_hair_care', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_hair_color', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['products.product_id'], name='properties_ibfk_1'),
    sa.PrimaryKeyConstraint('profile_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('viewed_brand')
    # ### end Alembic commands ###
