"""Updated database to latest ERD version

Revision ID: 7fb65e9a32f6
Revises: 2d53a67e4d71
Create Date: 2020-03-26 20:58:30.070331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fb65e9a32f6'
down_revision = '2d53a67e4d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_agent')
    op.add_column('sessions', sa.Column('browser_family', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('device_brand', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('is_bot', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('is_email_client', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('is_mobile', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('is_pc', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('is_tablet', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('is_touch', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('os_family', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'os_family')
    op.drop_column('sessions', 'is_touch')
    op.drop_column('sessions', 'is_tablet')
    op.drop_column('sessions', 'is_pc')
    op.drop_column('sessions', 'is_mobile')
    op.drop_column('sessions', 'is_email_client')
    op.drop_column('sessions', 'is_bot')
    op.drop_column('sessions', 'device_brand')
    op.drop_column('sessions', 'browser_family')
    op.create_table('user_agent',
    sa.Column('session_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('os_family', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('browser_family', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('device_brandutel', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_botutel', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_email_clientutel', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_mobileutel', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_pcutel', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_tableutel', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('istouchutel', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.profile_id'], name='user_agent_ibfk_1'),
    sa.PrimaryKeyConstraint('session_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
