"""Added viewed product size

Revision ID: cd45de908f14
Revises: 07162416247f
Create Date: 2020-03-24 17:08:59.523696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd45de908f14'
down_revision = '07162416247f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewed_product_size',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('product_size_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.profile_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewed_product_size')
    # ### end Alembic commands ###
