"""Changed Order to order

Revision ID: fb3e83670045
Revises: 2e9aaef8224f
Create Date: 2020-03-24 16:29:12.292611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb3e83670045'
down_revision = '2e9aaef8224f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Order')
    op.create_table('order',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.profile_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Order',
    sa.Column('session_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('product_id', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='Order_ibfk_1'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.profile_id'], name='Order_ibfk_2'),
    sa.PrimaryKeyConstraint('session_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('order')
    # ### end Alembic commands ###
