"""Added sessions and previously recommended

Revision ID: fbe394223913
Revises: 9649e0606161
Create Date: 2020-03-24 15:25:22.325568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe394223913'
down_revision = '9649e0606161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
