"""Added viewed sub sub category

Revision ID: fcc0716d8eff
Revises: a1f89e7c0600
Create Date: 2020-03-24 16:58:47.594480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc0716d8eff'
down_revision = 'a1f89e7c0600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewed_sub_sub_category',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('sub_sub_category_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.profile_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewed_sub_sub_category')
    # ### end Alembic commands ###
