"""Rearranged products table

Revision ID: 0b8bda90f62d
Revises: bc2f230181bc
Create Date: 2020-04-07 13:32:30.205117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8bda90f62d'
down_revision = 'bc2f230181bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
