"""Created terms table

Revision ID: 1588e0b04c48
Revises: 
Create Date: 2020-04-07 11:20:46.995724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1588e0b04c48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_terms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trend_terms')
    # ### end Alembic commands ###
