"""Removed id from products

Revision ID: dfa8514df19e
Revises: 0b8bda90f62d
Create Date: 2020-04-07 15:15:19.463143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfa8514df19e'
down_revision = '0b8bda90f62d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
