"""Added collaborative recommendations

Revision ID: e82efd385587
Revises: fb782042cc0a
Create Date: 2020-04-08 09:48:53.787259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82efd385587'
down_revision = 'fb782042cc0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborative_recommendations',
    sa.Column('profile_id', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.String(length=255), nullable=True),
    sa.Column('compatibility', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaborative_recommendations')
    # ### end Alembic commands ###
