"""Adding trend recommendations

Revision ID: fb782042cc0a
Revises: dfa8514df19e
Create Date: 2020-04-07 15:33:12.190021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb782042cc0a'
down_revision = 'dfa8514df19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_recommendations',
    sa.Column('product_id', sa.String(length=255), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['trend_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trend_recommendations')
    # ### end Alembic commands ###
